# fly.toml app configuration file
app = "job-applier-app"
primary_region = "iad"

[build]

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "job_applier.settings"
  GIT_PYTHON_REFRESH = "quiet"
  CHROME_BIN = "/usr/bin/chromium"
  CHROMEDRIVER_PATH = "/usr/bin/chromedriver"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "job_applier_data"
  destination = "/data"

[deploy]
  release_command = "python manage.py migrate"

[processes]
  app = "gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 job_applier.wsgi:application"
  worker = "celery -A job_applier worker --loglevel=info --concurrency=2"