app = "job-applier-app"
primary_region = "iad"

[build]
  [build.args]
    DJANGO_SECRET_KEY="@60hffxk70=y*m3$@gc+b)5oiy!smc!y4qzji#o4c_xy=)^k97"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "job_applier.settings"
  GIT_PYTHON_REFRESH = "quiet"
  CHROME_BIN = "/usr/bin/chromium"
  CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
  DATABASE_URL = "postgres://postgres:DwLdHitwpbbGc1y@job-applier-postgres.flycast:5432/job_applier_app"
  FLY_APP_NAME = "job-applier-app"
  SITE_DOMAIN = "job-applier-app.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[vm]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[[mounts]]
  source = "job_applier_data"
  destination = "/data"

[deploy]
  release_command = "python manage.py migrate --noinput"

[processes]
  app = "gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 job_applier.wsgi:application"
  worker = "celery -A job_applier worker --loglevel=info --concurrency=2"