# Generated by Django 5.1.7 on 2025-04-02 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("company", models.CharField(max_length=500)),
                ("location", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("glassdoor", "Glassdoor"),
                            ("monster", "Monster"),
                            ("jobbank", "JobBank"),
                            ("ziprecruiter", "ZipRecruiter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField()),
                ("posted_date", models.DateField()),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                ("job_type", models.CharField(blank=True, max_length=200)),
                ("experience_level", models.CharField(blank=True, max_length=200)),
                ("required_skills", models.JSONField(default=list)),
                ("preferred_skills", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                (
                    "tailored_resume",
                    models.FileField(blank=True, max_length=500, upload_to="tailored_resumes/"),
                ),
                (
                    "tailored_cover_letter",
                    models.FileField(
                        blank=True, max_length=500, upload_to="tailored_cover_letters/"
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("application_date", models.DateField(blank=True, null=True)),
                ("application_status", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-posted_date", "-match_score"],
                "indexes": [
                    models.Index(
                        fields=["title", "company", "location"], name="core_joblis_title_ec371d_idx"
                    ),
                    models.Index(fields=["posted_date"], name="core_joblis_posted__e48449_idx"),
                    models.Index(fields=["match_score"], name="core_joblis_match_s_1e2f7a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("headline", models.CharField(blank=True, max_length=100)),
                ("professional_summary", models.TextField(blank=True)),
                ("current_position", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                ("parsed_resume_data", models.JSONField(blank=True, default=dict)),
                ("github_data", models.JSONField(blank=True, default=dict)),
                ("last_github_refresh", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("frameworks", "Frameworks & Libraries"),
                            ("databases", "Databases"),
                            ("tools", "Tools & Technologies"),
                            ("soft_skills", "Soft Skills"),
                            ("languages", "Languages"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "-proficiency", "name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField()),
                ("publication_date", models.DateField()),
                ("publisher", models.CharField(max_length=200)),
                ("journal", models.CharField(blank=True, max_length=200)),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("technologies", models.TextField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("live_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="JobPlatformPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "preferred_platforms",
                    models.JSONField(
                        default=list, help_text="List of preferred job platforms from JOB_SOURCES"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_platform_preferences",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Platform Preference",
                "verbose_name_plural": "Job Platform Preferences",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("gpa", models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ("achievements", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                ("credential_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                ("achievements", models.TextField(blank=True)),
                ("technologies", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-order"],
            },
        ),
    ]
