# Generated by Django 5.0.2 on 2025-05-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LangGraphCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                ("checkpoint", models.BinaryField()),
                (
                    "parent_ts",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LangGraph Checkpoint",
                "verbose_name_plural": "LangGraph Checkpoints",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chatconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("indeed", "Indeed"),
                            ("glassdoor", "Glassdoor"),
                            ("monster", "Monster"),
                            ("jobbank", "JobBank"),
                            ("ziprecruiter", "ZipRecruiter"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("salary_range", models.CharField(blank=True, max_length=100, null=True)),
                ("job_type", models.CharField(blank=True, max_length=200, null=True)),
                ("benefits", models.TextField(blank=True, null=True)),
                ("experience_level", models.CharField(blank=True, max_length=200, null=True)),
                ("required_skills", models.JSONField(blank=True, default=list, null=True)),
                ("preferred_skills", models.JSONField(blank=True, default=list, null=True)),
                (
                    "tailored_resume",
                    models.FileField(
                        blank=True, max_length=500, null=True, upload_to="tailored_resumes/"
                    ),
                ),
                (
                    "tailored_cover_letter",
                    models.FileField(
                        blank=True, max_length=500, upload_to="tailored_cover_letters/"
                    ),
                ),
                ("applied", models.BooleanField(blank=True, default=False, null=True)),
                ("application_date", models.DateField(blank=True, null=True)),
                ("application_status", models.CharField(blank=True, max_length=200, null=True)),
                ("how_to_apply", models.TextField(blank=True, null=True)),
                ("match_details", models.JSONField(blank=True, default=list, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                ("match_score", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date", "-match_score"],
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="job_listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations",
                to="core.joblisting",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Full name - alternative to user.first_name and user.last_name",
                        max_length=200,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Professional title or role", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True, help_text="Full address")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True, help_text="Personal website URL")),
                ("github_url", models.URLField(blank=True, help_text="GitHub profile URL")),
                ("linkedin_url", models.URLField(blank=True, help_text="LinkedIn profile URL")),
                (
                    "headline",
                    models.CharField(blank=True, help_text="Professional headline", max_length=100),
                ),
                (
                    "professional_summary",
                    models.TextField(blank=True, help_text="Professional summary or bio"),
                ),
                ("current_position", models.CharField(blank=True, max_length=100)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                ("parsed_resume_data", models.JSONField(blank=True, default=dict)),
                ("github_data", models.JSONField(blank=True, default=dict)),
                ("last_github_refresh", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("programming", "Programming Languages"),
                            ("frameworks", "Frameworks & Libraries"),
                            ("databases", "Databases"),
                            ("tools", "Tools & Technologies"),
                            ("soft_skills", "Soft Skills"),
                            ("languages", "Languages"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.IntegerField(
                        choices=[
                            (1, "Beginner"),
                            (2, "Elementary"),
                            (3, "Intermediate"),
                            (4, "Advanced"),
                            (5, "Expert"),
                        ],
                        default=3,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "-proficiency", "name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=200, null=True)),
                ("journal", models.CharField(blank=True, max_length=200, null=True)),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("technologies", models.TextField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_url", models.URLField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="JobPlatformPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_platforms",
                    models.JSONField(default=list, help_text="List of preferred job platforms"),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_platform_preferences",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Platform Preference",
                "verbose_name_plural": "Job Platform Preferences",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(blank=True, max_length=200, null=True)),
                ("degree", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(blank=True, default=False, null=True)),
                ("gpa", models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("issuer", models.CharField(blank=True, max_length=200, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=100, null=True)),
                ("credential_url", models.URLField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("technologies", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-order"],
            },
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["title"], name="core_joblis_title_5b48e8_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["company"], name="core_joblis_company_b29189_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["posted_date"], name="core_joblis_posted__e48449_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["match_score"], name="core_joblis_match_s_1e2f7a_idx"),
        ),
    ]
