# Generated by Django 5.0.2 on 2025-05-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
