# Generated by Django 5.0.2 on 2025-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # UserProfile - ONLY last_github_refresh should be nullable (has null=True in model)
        # All other UserProfile fields have only blank=True, so they stay NOT NULL
        # WorkExperience fields - match profile.py exactly
        migrations.AlterField(
            model_name="workexperience",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="technologies",
            field=models.TextField(blank=True, null=True),
        ),
        # Project fields - match profile.py exactly
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, null=True),
        ),
        # Education fields - match profile.py exactly
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="current",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="gpa",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        # Certification fields - match profile.py exactly
        migrations.AlterField(
            model_name="certification",
            name="issuer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="credential_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="credential_url",
            field=models.URLField(blank=True, null=True),
        ),
        # Publication fields - match profile.py exactly
        migrations.AlterField(
            model_name="publication",
            name="authors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publisher",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="journal",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
