# Generated by Django 5.0.2 on 2025-06-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20250528_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, help_text="Personal website URL", null=True),
        ),
    ]
