# Generated by Django 5.1.7 on 2025-04-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_education_start_date"),
        ("core", "0003_update_education_start_date"),
    ]

    operations = []
