# Generated by Django 5.0.2 on 2025-06-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userprofile_github_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="current",
        ),
        migrations.RemoveField(
            model_name="project",
            name="current",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="current_position",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="current",
        ),
    ]
