# Generated by Django 5.0.2 on 2025-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_education_current_remove_project_current_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
