# Generated by Django 5.1.7 on 2025-04-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_certification_issue_date"),
        ("core", "0004_merge_20250406_1343"),
    ]

    operations = []
