# Generated by Django 5.2.3 on 2025-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_workexperience_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
