# Generated by Django 5.1.7 on 2025-04-01 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_years_of_experience_joblisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPlatformPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_platforms', models.JSONField(default=list, help_text='List of preferred job platforms from JOB_SOURCES')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Platform Preference',
                'verbose_name_plural': 'Job Platform Preferences',
            },
        ),
        migrations.RemoveIndex(
            model_name='joblisting',
            name='core_joblis_source_5c2ac1_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_github_fetch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('monster', 'Monster'), ('jobbank', 'JobBank'), ('ziprecruiter', 'ZipRecruiter'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='tailored_cover_letter',
            field=models.FileField(blank=True, max_length=500, upload_to='tailored_cover_letters/'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='tailored_resume',
            field=models.FileField(blank=True, max_length=500, upload_to='tailored_resumes/'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['match_score'], name='core_joblis_match_s_1e2f7a_idx'),
        ),
        migrations.AddField(
            model_name='jobplatformpreference',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_platform_preferences', to='core.userprofile'),
        ),
    ]
