# Generated by Django 5.1.7 on 2025-04-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobplatformpreference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_github_fetch',
            new_name='last_github_refresh',
        ),
    ]
