# Generated by Django 5.1.7 on 2025-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_certification_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
