# Generated by Django 5.0.2 on 2025-04-23 03:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_certification_issue_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="joblisting",
            name="core_joblis_title_ec371d_idx",
        ),
        migrations.RemoveIndex(
            model_name="joblisting",
            name="core_joblis_posted__e48449_idx",
        ),
        migrations.RemoveIndex(
            model_name="joblisting",
            name="core_joblis_match_s_1e2f7a_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="github",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
        migrations.AddField(
            model_name="certification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="certification",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="education",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="education",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="publication",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="publication",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="skill",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="jobplatformpreference",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="jobplatformpreference",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, help_text="Full address"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub profile URL"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="headline",
            field=models.CharField(blank=True, help_text="Professional headline", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Full name - alternative to user.first_name and user.last_name",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="professional_summary",
            field=models.TextField(blank=True, help_text="Professional summary or bio"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="title",
            field=models.CharField(
                blank=True, help_text="Professional title or role", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, help_text="Personal website URL"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["user", "is_active"], name="core_joblis_user_id_236cfd_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["user", "applied"], name="core_joblis_user_id_96ee83_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["user", "match_score"], name="core_joblis_user_id_73fde1_idx"
            ),
        ),
    ]
