# Generated by Django 5.0.2 on 2025-04-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_consolidate_fields"),
    ]

    operations = []
