# Generated by Django 5.0.2 on 2025-04-23 03:34

from django.db import migrations


def migrate_user_profile_fields(apps, schema_editor):
    """
    Move data from removed fields to consolidated fields
    Fields removed: bio, email, github, linkedin, location
    Consolidated into: professional_summary, github_url, linkedin_url, address
    """
    UserProfile = apps.get_model("core", "UserProfile")

    for profile in UserProfile.objects.all():
        # Handle bio field - consolidate into professional_summary
        if hasattr(profile, "bio") and profile.bio and not profile.professional_summary:
            profile.professional_summary = profile.bio

        # Handle github field - consolidate into github_url
        if hasattr(profile, "github") and profile.github and not profile.github_url:
            profile.github_url = profile.github

        # Handle linkedin field - consolidate into linkedin_url
        if hasattr(profile, "linkedin") and profile.linkedin and not profile.linkedin_url:
            profile.linkedin_url = profile.linkedin

        # Handle location field - consolidate into address
        if hasattr(profile, "location") and profile.location and not profile.address:
            profile.address = profile.location

        # Email field will be removed since users already have email in the User model

        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_migrate_data_after_consolidation"),
    ]

    operations = [
        migrations.RunPython(migrate_user_profile_fields, migrations.RunPython.noop),
    ]
