# Generated by Django 5.0.2 on 2025-04-25 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_data_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="joblisting",
            name="core_joblis_user_id_236cfd_idx",
        ),
        migrations.RemoveIndex(
            model_name="joblisting",
            name="core_joblis_user_id_96ee83_idx",
        ),
        migrations.RemoveIndex(
            model_name="joblisting",
            name="core_joblis_user_id_73fde1_idx",
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="company",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="posted_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobplatformpreference",
            name="preferred_platforms",
            field=models.JSONField(default=list, help_text="List of preferred job platforms"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                choices=[
                    (1, "Beginner"),
                    (2, "Elementary"),
                    (3, "Intermediate"),
                    (4, "Advanced"),
                    (5, "Expert"),
                ],
                default=3,
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["title"], name="core_joblis_title_5b48e8_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["company"], name="core_joblis_company_b29189_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["posted_date"], name="core_joblis_posted__e48449_idx"),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(fields=["match_score"], name="core_joblis_match_s_1e2f7a_idx"),
        ),
    ]
