# Generated by Django 5.0.2 on 2025-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_joblisting_core_joblis_user_id_236cfd_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
