# Generated by Django 5.0.2 on 2025-04-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_joblisting_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="application_status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="applied",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="experience_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="job_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="posted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="preferred_skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="required_skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("indeed", "Indeed"),
                    ("glassdoor", "Glassdoor"),
                    ("monster", "Monster"),
                    ("jobbank", "JobBank"),
                    ("ziprecruiter", "ZipRecruiter"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="source_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="tailored_resume",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="tailored_resumes/"
            ),
        ),
    ]
