# Generated by Django 5.0.2 on 2025-04-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_joblisting_application_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("indeed", "Indeed"),
                    ("glassdoor", "Glassdoor"),
                    ("monster", "Monster"),
                    ("jobbank", "JobBank"),
                    ("ziprecruiter", "ZipRecruiter"),
                    ("other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
