# Generated by Django 5.0.2 on 2025-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_joblisting_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="how_to_apply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
