# Generated by Django 5.0.2 on 2025-04-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_certification_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LangGraphCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("thread_id", models.CharField(db_index=True, max_length=255)),
                ("checkpoint", models.BinaryField()),
                (
                    "parent_ts",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "LangGraph Checkpoint",
                "verbose_name_plural": "LangGraph Checkpoints",
                "ordering": ["-updated_at"],
            },
        ),
    ]
