# Generated by Django 5.0.2 on 2025-04-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_langgraphcheckpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="joblisting",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
