# Generated by Django 5.0.2 on 2025-04-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_joblisting_company_alter_joblisting_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblisting",
            name="source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
