# Generated by Django 5.0.2 on 2025-05-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_joblisting_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="benefits",
            field=models.TextField(blank=True, null=True),
        ),
    ]
