# Generated by Django 5.0.2 on 2025-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_joblisting_benefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="gaps",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="joblisting",
            name="stengths",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
