# Generated by Django 5.0.2 on 2025-05-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_joblisting_gaps_joblisting_stengths"),
    ]

    operations = [
        migrations.RenameField(
            model_name="joblisting",
            old_name="gaps",
            new_name="match_details",
        ),
        migrations.RemoveField(
            model_name="joblisting",
            name="stengths",
        ),
    ]
