# Generated by Django 5.0.2 on 2025-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_rename_gaps_joblisting_match_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="authors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
