# Generated by Django 5.0.2 on 2025-05-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_publication_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
