# Generated by Django 5.0.2 on 2025-05-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_alter_workexperience_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="technologies",
            field=models.TextField(blank=True, null=True),
        ),
    ]
