# Generated by Django 5.0.2 on 2025-05-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_certification_credential_id_and_more"),
    ]

    operations = []
