# Generated by Django 5.0.2 on 2025-05-28 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_fix_joblisting_indexes"),
    ]

    operations = []
